"use client";
import React, { useState } from "react";

const GeneratorPage = () => {
  const [prompt, setPrompt] = useState("");
  const [generatedCode, setGeneratedCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleGenerate = (e) => {
    e.preventDefault();
    if (!prompt.trim()) {
      setError("Please enter a prompt!");
      return;
    }

    setError("");
    setLoading(true);
    setGeneratedCode("");

    // Simulate AI generation delay
    setTimeout(() => {
      const dummyCode = `
      // ✨ Example code generated from your prompt:
      import React from 'react';
      import './App.css';
      
      const GeneratedComponent = () => {
        return (
          <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
            <h1 className="text-3xl font-bold text-blue-600 mb-4">
              ${prompt}
            </h1>
            <p className="text-gray-700">This is a sample UI generated by AI.</p>
            <button className="mt-4 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
              Click Me
            </button>
          </div>
        );
      };

      export default GeneratedComponent;
      `;
      setGeneratedCode(dummyCode);
      setLoading(false);
    }, 1500);
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center py-10 px-4">
      <div className="w-full max-w-4xl bg-white shadow-xl rounded-2xl p-8 border border-gray-200">
        <h1 className="text-2xl font-semibold text-gray-800 mb-6 text-center">
          <span role="img" aria-label="brain" className="mr-2">🧠</span>
            SNAP UI - AI-Powered Code Generator
        </h1>

        {/* Prompt Input */}
        <form onSubmit={handleGenerate} className="space-y-4">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Describe what you want to generate (e.g., a responsive navbar using React and Tailwind)..."
            className="w-full border border-gray-300 rounded-lg p-4 text-gray-800 focus:ring-2 focus:ring-blue-500 focus:outline-none resize-none"
            rows={5}
          />
          {error && <p className="text-red-500 text-sm">{error}</p>}

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-4 rounded-lg transition"
          >
            {loading ? "Generating..." : "Generate Code"}
          </button>
        </form>

        {/* Output Area */}
        <div className="mt-8">
          <h2 className="text-lg font-semibold text-gray-700 mb-3">
            Generated Code:
          </h2>

          {loading ? (
            <p className="text-gray-500 italic">AI is generating code...</p>
          ) : generatedCode ? (
            <pre className="bg-gray-900 text-green-400 p-4 rounded-lg overflow-x-auto text-sm whitespace-pre-wrap">
              {generatedCode}
            </pre>
          ) : (
            <p className="text-gray-400">No code generated yet.</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default GeneratorPage;
