// frontend/src/app/user/generator/[id]/page.jsx
'use client';
import React, { useEffect, useState, useRef } from "react";
import Link from "next/link";
import { useParams, useRouter } from 'next/navigation';

export default function GeneratorPageClient() {
  const params = useParams();            // { id: '...' }
  const router = useRouter();
  const projectId = params?.id || null;

  const [prompt, setPrompt] = useState("");
  const [generatedCode, setGeneratedCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [project, setProject] = useState(null);
  const [fetchingProject, setFetchingProject] = useState(false);
  const mountedRef = useRef(false);

  // Fetch project metadata from backend (GET /api/projects)
  useEffect(() => {
    mountedRef.current = true;
    async function getProject() {
      if (!projectId) return;
      setFetchingProject(true);
      try {
        const res = await fetch('/api/projects'); // server route returns list (earlier route)
        if (!res.ok) {
          const err = await res.json().catch(()=>({ error: 'Failed' }));
          throw new Error(err?.error || `HTTP ${res.status}`);
        }
        const body = await res.json();
        const found = (body.projects || []).find(p => String(p.id) === String(projectId));
        if (found) {
          setProject(found);
          // If the project has a useful title, prefill prompt so user can hit Generate.
          if (!prompt.trim()) {
            setPrompt(found.title || '');
          }
        } else {
          setProject(null);
        }
      } catch (err) {
        console.error('Failed to fetch project', err);
        setError('Could not load project metadata');
      } finally {
        if (mountedRef.current) setFetchingProject(false);
      }
    }
    getProject();
    return () => { mountedRef.current = false; };
  }, [projectId]);

  // Handle generate action (currently local mock generation; replace with API call if desired)
  const handleGenerate = async (e) => {
    e?.preventDefault?.();
    if (!prompt.trim()) {
      setError("Please enter a prompt!");
      return;
    }
    setError("");
    setLoading(true);
    setGeneratedCode("");

    try {
      // Example: call your AI endpoint here instead of mock
      // const res = await fetch('/api/generate-ui', { method: 'POST', body: JSON.stringify({ prompt }) })
      // ... handle real response ...
      // For now, keep the mock behavior you had but include project id in generated comments:

      await new Promise(r => setTimeout(r, 1200)); // simulate delay

      const dummyCode = `// Generated for project: ${projectId || 'local'}\n\n// ✨ Example code generated from your prompt:\nimport React from 'react';\nimport './App.css';\n\nconst GeneratedComponent = () => {\n  return (\n    <div className=\"flex flex-col items-center justify-center min-h-screen bg-[#0a0a0a]\">\n      <h1 className=\"text-3xl font-bold text-[#00ff88] mb-4\">\n        ${escapeForTemplate(prompt)}\n      </h1>\n      <p className=\"text-gray-300\">This is a sample UI generated by AI.</p>\n      <button className=\"mt-4 px-6 py-2 bg-[#f6ff00] text-black rounded-lg hover:brightness-95 transition\">\n        Click Me\n      </button>\n    </div>\n  );\n};\n\nexport default GeneratedComponent;\n`;
      setGeneratedCode(dummyCode.trim());
    } catch (err) {
      console.error(err);
      setError(err?.message || 'Generation failed');
    } finally {
      setLoading(false);
    }
  };

  // Helper to download generated code
  function downloadGenerated() {
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `generated-${projectId || 'component'}.js`;
    a.click();
    URL.revokeObjectURL(url);
  }

  // If no id present, redirect user back to dashboard (optional)
  useEffect(() => {
    if (!projectId) {
      // no id in url — we keep user here but could redirect to /dashboard
      // router.push('/dashboard');
    }
  }, [projectId]);

  return (
    <>
      {/* Navbar */}
      <nav className="w-full bg-[#070707] border-b border-[#111]">
        <div className="max-w-7xl mx-auto flex items-center justify-between px-4 py-4">
          <div className="flex items-center gap-4">
            <Link href="/" className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#002b00] to-[#003800] flex items-center justify-center shadow-[0_0_18px_rgba(0,255,136,0.12)]">
                <span className="text-[#00ff88] font-extrabold">SNAP</span>
              </div>
              <div>
                <div className="text-[#00ff88] font-bold">SnapUI</div>
                <div className="text-xs text-gray-400">Code · UI · Generator</div>
              </div>
            </Link>

            {/* show project id in navbar if available */}
            {projectId && (
              <div className="ml-4 text-xs text-gray-400">
                Project: <span className="text-yellow-400 font-medium">{projectId}</span>
              </div>
            )}
          </div>

          <div className="flex items-center gap-3">
            <Link href="/dashboard" className="text-sm px-3 py-1 rounded-md text-[#bfffc4] hover:text-white">
              Dashboard
            </Link>
            <Link href="/user/project-manager" className="text-sm px-3 py-1 rounded-md text-[#bfffc4] hover:text-white">
              Project Manager
            </Link>
            <Link href="/user/profile" className="text-sm px-3 py-1 rounded-md text-[#bfffc4] hover:text-white">
              Profile
            </Link>
            <Link href="/templates" className="ml-2 inline-flex items-center gap-2 px-3 py-1 rounded-md bg-[#0b0b0b] border border-[#1a1a1a] text-yellow-400 hover:shadow-[0_0_12px_rgba(246,255,0,0.08)]">
              Templates
            </Link>
          </div>
        </div>
      </nav>

      {/* Page content */}
      <div className="min-h-screen bg-[#0a0a0a] text-gray-200 flex flex-col items-center py-12 px-4">
        <div className="w-full max-w-4xl rounded-2xl p-8 bg-gradient-to-b from-[#070707] to-[#0f0f0f] border border-[#111] shadow-[0_10px_40px_rgba(0,0,0,0.6)]">
          <div className="flex flex-col md:flex-row items-center md:items-start justify-between gap-6">
            <div className="flex-1">
              <h1 className="text-2xl font-bold text-[#00ff88] mb-2 flex items-center gap-3">
                <span className="inline-flex w-9 h-9 items-center justify-center rounded-lg bg-[#001f00] shadow-[0_0_12px_rgba(0,255,136,0.06)] text-xl">🧠</span>
                SNAP UI — AI-Powered Code Generator
              </h1>
              <p className="text-sm text-gray-400">
                {project ? (
                  <>Working on project <span className="text-yellow-400 font-medium">{project.title}</span> — edit the prompt below and generate.</>
                ) : fetchingProject ? (
                  <>Loading project metadata…</>
                ) : (
                  <>Describe what you want and SnapUI will generate a starter component or boilerplate. Try: <span className="text-yellow-400">"responsive navbar with auth modal"</span></>
                )}
              </p>
            </div>

            <div className="flex-shrink-0 hidden md:block">
              <Link href="/dashboard" className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-[#f6ff00] text-black font-semibold shadow-[0_6px_20px_rgba(246,255,0,0.12)] hover:brightness-95 transition">
                Go to Dashboard
              </Link>
            </div>
          </div>

          {/* Project header / meta */}
          <div className="mt-6 flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="text-sm text-gray-400">
                <div>Project ID: <span className="text-yellow-400">{projectId || '—'}</span></div>
                {project && (
                  <div className="text-xs text-gray-500">Status: <span className="text-yellow-400">{project.status}</span> · Created: <span className="text-gray-400">{new Date(project.createdAt).toLocaleString()}</span></div>
                )}
              </div>
            </div>

            <div className="text-xs text-gray-500">{project ? 'Project loaded' : 'No project data'}</div>
          </div>

          {/* Prompt Input */}
          <form onSubmit={handleGenerate} className="mt-6 space-y-4">
            <label className="sr-only">Prompt</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={project ? `Generate UI for project "${project.title}" (edit the prompt to be more specific)...` : "Describe what you want to generate (e.g., a responsive navbar using React and Tailwind)..."}
              className="w-full bg-[#080808] border border-[#1a1a1a] rounded-lg p-4 text-gray-200 focus:outline-none focus:shadow-[0_0_12px_rgba(0,255,136,0.08)] resize-none min-h-[140px]"
              rows={5}
            />
            {error && <p className="text-red-400 text-sm">{error}</p>}

            <div className="flex flex-col sm:flex-row gap-3">
              <button
                type="submit"
                disabled={loading}
                className="flex-1 inline-flex items-center justify-center gap-2 bg-[#f6ff00] text-black font-medium py-3 px-4 rounded-lg hover:brightness-95 transition disabled:opacity-60"
              >
                {loading ? (
                  <>
                    <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none">
                      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" className="text-black/30"></circle>
                      <path d="M22 12a10 10 0 00-10-10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"></path>
                    </svg>
                    Generating...
                  </>
                ) : (
                  "Generate Code"
                )}
              </button>

              <Link href="/user/project-manager" className="inline-flex items-center justify-center gap-2 px-4 py-3 rounded-lg border border-[#1a1a1a] bg-[#050505] text-[#bfffc4] hover:shadow-[0_0_12px_rgba(0,255,136,0.06)]">
                Project Manager
              </Link>
            </div>
          </form>

          {/* Output Area */}
          <div className="mt-8">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-lg font-semibold text-[#00ff88]">Generated Code</h2>
              <div className="text-xs text-gray-400">Tip: copy & paste into a component file</div>
            </div>

            <div className="rounded-lg border border-[#1a1a1a] overflow-hidden">
              {loading ? (
                <div className="p-6 flex items-center justify-center bg-[#070707]">
                  <p className="text-gray-400 italic">AI is generating code...</p>
                </div>
              ) : generatedCode ? (
                <pre className="m-0 p-4 bg-[#030303] text-sm text-[#bfffc4] overflow-x-auto whitespace-pre-wrap">
                  {generatedCode}
                </pre>
              ) : (
                <div className="p-6 bg-[#070707] text-gray-400">
                  No code generated yet. Try entering a prompt and clicking <span className="text-yellow-400 font-medium">Generate Code</span>.
                </div>
              )}
            </div>

            {/* actions: copy & download */}
            {generatedCode && (
              <div className="mt-3 flex gap-3">
                <button
                  onClick={() => navigator.clipboard?.writeText(generatedCode)}
                  className="px-3 py-2 rounded-md bg-[#00ff88] bg-opacity-10 text-[#00ff88] border border-[#0f4a20] hover:shadow-[0_0_10px_rgba(0,255,136,0.08)]"
                >
                  Copy
                </button>
                <button onClick={downloadGenerated} className="px-3 py-2 rounded-md bg-[#f6ff00] text-black font-medium">
                  Download
                </button>
              </div>
            )}
          </div>

          {/* ---------- Templates Section ---------- */}
          <div className="mt-10">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-[#00ff88]">Templates</h3>
              <Link href="/templates" className="text-sm text-yellow-400 hover:underline">See all templates →</Link>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {/* example templates - keep same as before or fetch dynamically */}
              <Link key="responsive-navbar" href={`/templates/responsive-navbar`} className="block p-4 rounded-lg border border-[#1a1a1a] bg-[#070707] hover:shadow-[0_10px_30px_rgba(0,255,136,0.04)] transition">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-sm font-semibold text-[#bfffc4]">Responsive Navbar</h4>
                    <p className="text-xs text-gray-400 mt-1">Navbar with mobile menu + auth modal</p>
                  </div>
                  <div className="text-yellow-400 text-xs font-medium">Use</div>
                </div>
              </Link>

              <Link key="auth-modal" href={`/templates/auth-modal`} className="block p-4 rounded-lg border border-[#1a1a1a] bg-[#070707] hover:shadow-[0_10px_30px_rgba(0,255,136,0.04)] transition">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-sm font-semibold text-[#bfffc4]">Auth Modal</h4>
                    <p className="text-xs text-gray-400 mt-1">Sign-in / sign-up modal UI</p>
                  </div>
                  <div className="text-yellow-400 text-xs font-medium">Use</div>
                </div>
              </Link>

              <Link key="dashboard-card" href={`/templates/dashboard-card`} className="block p-4 rounded-lg border border-[#1a1a1a] bg-[#070707] hover:shadow-[0_10px_30px_rgba(0,255,136,0.04)] transition">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-sm font-semibold text-[#bfffc4]">Dashboard Card</h4>
                    <p className="text-xs text-gray-400 mt-1">Info card with chart placeholder</p>
                  </div>
                  <div className="text-yellow-400 text-xs font-medium">Use</div>
                </div>
              </Link>
            </div>
          </div>
          {/* ---------- end Templates Section ---------- */}

        </div>

        {/* Footer */}
        <div className="mt-8 text-xs text-gray-500">
          v1.0 • Build 2025 • &copy; 2024 SnapUI Inc.
        </div>
      </div>
    </>
  );
}

/* ---------- helpers ---------- */

function escapeForTemplate(s = '') {
  return String(s).replace(/`/g, '\\`').replace(/\$/g, '\\$');
}
