const mongoose = require("mongoose");

const ProjectSchema = new mongoose.Schema(
  {
    // Project ID generated by backend
    projectId: {
      type: String,
      required: true,
      unique: true,
    },

    // Project name from user
    name: {
      type: String,
      required: true,
    },

    // Selected template / UI type
    type: {
      type: String,
    },

    // Full generated code
    generatedCode: {
      type: String,
      default: "",
    },

    // Any user customizations (optional)
    settings: {
      type: Object,
      default: {},
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Project", ProjectSchema);
